import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateEnviosTable1761109891920 implements MigrationInterface {
    name = 'CreateEnviosTable1761109891920'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "envios" ("id" number GENERATED BY DEFAULT AS IDENTITY, "cliente_id" number, "origen_id" number NOT NULL, "destino_id" number NOT NULL, "remitente_nombre" varchar2(100) NOT NULL, "remitente_telefono" varchar2(20), "remitente_documento" varchar2(20), "remitente_email" varchar2(100), "tracking_code" varchar2(20) NOT NULL, "costo_total" number(10,2) NOT NULL, "metodo_envio" varchar2(20) DEFAULT 'terrestre' NOT NULL, "estado" varchar2(30) DEFAULT 'registrado' NOT NULL, "fecha_creacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "UQ_9574170c3715989c16c886563d1" UNIQUE ("tracking_code"), CONSTRAINT "PK_c3e39ce11196eaf350b50652227" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "envios"`);
    }

}
