-- Crear el esquema ADMIN si no existe
CREATE USER ADMIN IDENTIFIED BY admin123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- Otorgar permisos necesarios
GRANT CREATE SESSION TO ADMIN;
GRANT CREATE TABLE TO ADMIN;
GRANT CREATE SEQUENCE TO ADMIN;
GRANT CREATE TRIGGER TO ADMIN;

-- Conectar como el usuario ADMIN
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

-- Crear la tabla ENVIOS
CREATE TABLE ADMIN.ENVIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER,
    ORIGEN_ID NUMBER NOT NULL,
    DESTINO_ID NUMBER NOT NULL,
    REMITENTE_NOMBRE VARCHAR2(100) NOT NULL,
    REMITENTE_TELEFONO VARCHAR2(20),
    REMITENTE_DOCUMENTO VARCHAR2(20),
    REMITENTE_EMAIL VARCHAR2(100),
    TRACKING_CODE VARCHAR2(20) NOT NULL UNIQUE,
    COSTO_TOTAL NUMBER(10,2) NOT NULL,
    METODO_ENVIO VARCHAR2(20),
    ESTADO VARCHAR2(30),
    FECHA_CREACION TIMESTAMP
);